# Generated by Django 5.0.4 on 2024-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
