# Generated by Django 5.0.4 on 2024-05-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_songs_song_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='cover',
            new_name='song',
        ),
    ]
