# Generated by Django 5.0.4 on 2024-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_cover_song_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='cover',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
